### ISSUE TITLE
support tensorflow version 2.0-2.4

### ISSUE THREAD

**Issue by llpin1992** [martinsbruveris/tensorflow-image-models#55]
when i install tfimm, it need tensorflow version <3.0,>=2.5 , please support tf version 2.0-2.4

**Comment by martinsbruveris** [comment]
It could be that I am more restrictive with the TF version than I have to be. At the same time several of the models are using grouped convolutions and those were only introduced fairly recently in TF. I will see what happens if I run the unit tests with TF 2.4 or lower.

**Comment by llpin1992** [comment]
ok, thanks, expect your results!
