### ISSUE TITLE
[FEATURE REQUEST] EfficientNet models

### ISSUE THREAD

**Issue by benihime91** [martinsbruveris/tensorflow-image-models#65]
Is there any plan to add efficientnet V1x or V2x models ? I know implementations can be found in the keras module itself but adding these models would make this library trully the equivalent of ross's pytorch-image-models.

**Comment by martinsbruveris** [comment]
Yes, there is a plan to port the efficientnet models from `timm` as well. It is a bigger chunk of work. If all goes well, I hope to have a new version of `tfimm` with efficientnet models published in April... 🤞 ...

**Comment by benihime91** [comment]
Great
